### ISSUE TITLE
Change initial revision version number

### ISSUE THREAD

**Issue by thesunny** [stackiva/slate-collaborate-support#23]
When a document is first edited in Slate Collaborate, it gets a `revision` value of `0`. After each change, the revision is incremented by `1`.

Later (although not at time of writing) the document is cleaned up (i.e. removed from Redis), then a new editing session is started on the document, its `revision` will again be set to `0`.

The issue is that if we have an `onDocumentChange`, this method may be called from multiple editing sessions. This means that multiple editing sessions are firing off these events and one of the purposes of `onDocumentChange` is to save the changes live into the database. The problem is that the saves are not necessarily going to be pushed to the database in order due to differing latency from the Slate Collaborate Server to the applications database. To prevent this issue, we can make it a requirement that the save only happens if the `revision` saved in the database is less than that of the incoming one.

However, this only works if we can guarantee that the `revision` version is always going up. To ensure this, what we want is that when the document is first created, the `revision` value is set to `(new Date()).getTime()` which is the `ms` since epoch.

There is a small data leakage issue in that the `revision` number basically contains the edit start time, but that doesn't seem like it's an important leakage of data.

**Comment by wleroux** [comment]
The initial revision will be using the number of milliseconds since epoch for documents. This should support the use-case where the revision is used to determine the most up-to-date document.

There is a caveat with this approach: If there are more than 1000 changesets per second since the document creation, it is possible for a new document to have an initial revision that is "lower" than the last edit. This is not a realistic pattern of behavior we are expecting but it could potentially break the heuristic, so I am noting it here.
