### ISSUE TITLE
Document should be deleted when the last session expires

### ISSUE THREAD

**Issue by wleroux** [stackiva/slate-collaborate-support#3]

**Comment by thesunny** [comment]
Currently, when all editing sessions are ended, the Slate Collaborate server remembers the last session.

This is an issue because it's possible that some other process edits the content in the database.

When the user goes to edit the content, the content is what is on the Slate Collaborate server, and not in the database.

By making this change, we ensure that the database remains the overall source of truth, and the Slate Collaborate server only remains the source of truth while in the middle of an editing session.

**Comment by PaddyMann** [comment]
Will this update guarantee that all the cache gets cleared for all documents? 

I'm wondering...:
- What will happen if the redis server unexpectedly crashed/restarted after the last update, but before the cleanup operation?
- What will happen to any documents that are cached before this bug is fixed?

The second issue could prove a problem for us if we activate slate-collaborate for a customer's workspace using a feature flag, and then later deactivate it. If we then reactivate it later, the old document versions may be stored in cache leading to undesired behavior.

I hope that makes sense — please shout if not :)

**Comment by wleroux** [comment]
I haven't started looking into specific designs to meet these requirements... But what will probably be done is that if a session is attempted on a document and the last session expired over 5 minutes ago, it would delete the old document and create a new document instead. (In addition to deleting the old document after 5 minutes since the last session expired... However if the server stops within those five minutes, it may remain there.)

**Comment by thesunny** [comment]
Design proposal:

*   Each node server with a connection to Redis sends a keep alive to Redis which updates a `lastKeepAlive` value on the Redis server.
*   Each node server also at one minute intervals, queries for `lastKeepAlive` that is older than 2 minutes. EDIT: Each node server will also check `lastKeepAlive` on startup before allowing any new editing sessions to start.
*   If the `lastKeepAlive` on an editing session is older than 2 minutes, the editing session is closed. Assuming that there is config code on how to handle a closing editing session (which can be configured as per other design docs), then that session data can update the application's database.

Let's see how this handles the edge cases...

*   Redis server goes down.
*   It comes up but no node server has deleted the session yet because the one minute interval hasn't arrived yet
*   A new editing session connects. There is an existing editing session on that document. The new editing session uses the document from inside Redis.

I think that's the behavior we want because it prevents the earlier editing session from losing its edits. And when the new user starts editing a document that has unsaved edits, we want him/her to see the updated document not the stale one.

**Comment by PaddyMann** [comment]
With your design proposal, what happens if the node server goes down? 🤔

**Comment by thesunny** [comment]
Hi Paddy,

If the node server goes down:

*   If you're running more than one node server which you would do if high availability is a priority, then any of the other node servers would also be checking `lastKeepAlive` every minute (or custom interval) so it wouldn't change the outcome.
*   If you're running one node server, it also shouldn't change the outcome because when it comes online, the node server should check the `lastKeepAlive` expiry before allowing any connections. That should be added to the spec though which I will do now.

**Comment by wleroux** [comment]
We want to add a configuration to the server settings to keep the document around in the case of a new session appearing before the onDocumentSessionEnd updates the persistent datasource.

**Comment by wleroux** [comment]
Released as part of `0.0.19`
