### ISSUE TITLE
Non-memoized user information should not cause a reconnection if the data is the same

### ISSUE THREAD

**Issue by wleroux** [stackiva/slate-collaborate-support#4]

**Comment by thesunny** [comment]
Currently, we provide `params` prop to `useCollaborativeEditor`; however, if `params` is not memoized (which is easy to forget), the collaborative plugin tries to reconnect on every redraw.

**Comment by thesunny** [comment]
Hi @wleroux, when you close the issue, can you put a comment on why it was closed. I assume this was completed, but I think it may be unclear for users that are following the issue. Thank you.

Also, in the case that this was closed due to it being completed, can you put a short description on how the solution works which will be helpful to users following the issue.

**Comment by wleroux** [comment]
Updated the `@slate-collaborate/plugin` to evaluate the params using deep equality rather than object identity to prevent reconnections on every render.

```
    const editor = useMemo(() => withReact(createEditor()), []);
    const {ready, value, selection, onChange} = useCollaborativeEditor({
        serviceURL: "ws://demo.stackiva.com:8080/",
        editor,
        documentId,
        param: { username: "test" },
        initialValue: [{
            children: [{text: "Hello, World!"}]
        }]
    });
```
